apiVersion: apps/v1
kind: Deployment
metadata:
  name: retail-app
  namespace: retail-app
spec:
  replicas: 3
  selector:
    matchLabels:
      app: retail-store
  template:
    metadata:
      labels:
        app: retail-store
    spec:
      containers:
      - name: main-app
        image: public.ecr.aws/docker/library/nginx:latest # Placeholder for your ECR image
        ports:
        - containerPort: 80
---
apiVersion: v1
kind: Service
metadata:
  name: retail-service
  namespace: retail-app
spec:
  type: LoadBalancer
  selector:
    app: retail-store
  ports:
  - protocol: TCP
    port: 80
    targetPort: 80
